AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFormation template to create an SQS queue and an S3 bucket'

Resources:
  IngestQueue:
    Type: 'AWS::SQS::Queue'
    Properties:
      VisibilityTimeout: 70
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt IngestDeadLetterQueue.Arn
        maxReceiveCount: 5

  IngestDeadLetterQueue:
    Type: 'AWS::SQS::Queue'
    Properties:
      MessageRetentionPeriod: 1209600

  VideoBucket:
    Type: 'AWS::S3::Bucket'

  ArtifactBucket:
    Type: 'AWS::S3::Bucket'

  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: S3MultipartUploadPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:CreateMultipartUpload
                  - s3:PutObject
                  - s3:UploadPart
                  - s3:CompleteMultipartUpload
                  - s3:AbortMultipartUpload
                Resource: !Sub 'arn:aws:s3:::${VideoBucket}/*'

Outputs:
  QueueURL:
    Description: 'URL of the SQS Queue'
    Value: !Ref IngestQueue
  QueueARN:
    Description: 'ARN of the SQS Queue'
    Value: !GetAtt IngestQueue.Arn
  VideoBucketName:
    Description: 'Name of the S3 Bucket'
    Value: !Ref VideoBucket
  ArtifactBucketName:
    Description: 'Name of the S3 Bucket'
    Value: !Ref ArtifactBucket
  LambdaExecutionRoleARN:
    Description: 'ARN of the Lambda Execution IAM Role'
    Value: !GetAtt LambdaExecutionRole.Arn
  DeadLetterQueueURL:
    Description: 'URL of the Dead Letter Queue'
    Value: !Ref IngestDeadLetterQueue
  UserPoolId:
    Description: "The ID of the Cognito User Pool"
    Value: !Ref CognitoUserPool
    Export:
      Name: "CognitoUserPoolId"
  UserPoolClientId:
    Description: "The Client ID of the Cognito User Pool Client"
    Value: !Ref CognitoUserPoolClient
    Export:
      Name: "CognitoUserPoolClientId"